---
title: "Structure of combined Fude Polygon data with agricultural community boundary data"

output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Structure of combined Fude Polygon data with agricultural community boundary data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Structure of combined Fude Polygon data with agricultural community boundary data

```{r echo = FALSE, warning = FALSE, message = FALSE}
library(fude)
d <- read_fude("~/2022_38.zip", quiet = TRUE, supplementary = TRUE)
b <- get_boundary(d, path = "~", quiet = TRUE)
db <- combine_fude(d, b, city = "松山市", kcity = "浅海")
```

There are `r length(names(db))` types of objects obtained by `combine_fude()`, as follows:
```{r}
names(db)
```

# Possible values for `rcom` in `combine_fude()` and `extract_boundary()`

```{r rcom_in_data, echo = TRUE, warning = FALSE, message = FALSE, dpi = 150}
library(dplyr)
library(data.tree)

tree <- b[[1]] |>
  filter(grepl("松山", KCITY_NAME)) |>
  mutate(pathString = paste(PREF_NAME, CITY_NAME, KCITY_NAME, RCOM_NAME, sep = "/")) |>
  data.tree::as.Node()

tree$Do(\(node) {node$n <- if (node$isLeaf) NA_integer_ else node$count})
data.tree::SetFormat(tree, "n", \(x) if (is.na(x)) "-" else x)
print(tree, "n", limit = 30)

library(ggplot2)

ggplot(data = b[[1]] |> filter(grepl("松山", KCITY_NAME))) + 
  geom_sf(fill = NA) +
  geom_sf_text(aes(label = RCOM_NAME), size = 2, family = "Hiragino Sans") +
  theme_void()
```

**出典**：`r cite_fude(b)$ja`

```{r rcom_in_data_tree, echo = TRUE, warning = FALSE, message = FALSE, dpi = 150}
library(collapsibleTree)

b[[1]] |>
  filter(grepl("松山", CITY_NAME)) |>
  distinct(PREF_NAME, CITY_NAME, KCITY_NAME, RCOM_NAME) |>
  (\(x) collapsibleTree(
    x,
    hierarchy = names(x),
    root = "・"
  ))()
```

# Possible values for `kcity` in `combine_fude()` and `extract_boundary()`

```{r kcity_in_data, echo = TRUE, warning = FALSE, message = FALSE, dpi = 150}
library(paletteer)

ggplot(b[[1]] |> filter(CITY_NAME == "松山市")) +
  geom_sf(aes(fill = KCITY_NAME), alpha = .8) +
  theme_void() +
  theme(text = element_text(family = "Hiragino Sans")) +
  paletteer::scale_fill_paletteer_d("Polychrome::kelly")
```

**出典**：`r cite_fude(b)$ja`
