---
title: "Using `gghighlight` Package"

output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Using `gghighlight` Package}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Using `gghighlight` package

```{r echo = FALSE, warning = FALSE}
library(fude)
d <- read_fude("~/MB0001_2025_2020_38.zip", quiet = TRUE, supplementary = TRUE)
b <- get_boundary(d, path = "~", quiet = TRUE)
```

```{r facet_wrap_gogoshima, echo = TRUE, warning = FALSE, message = FALSE, dpi = 150}
library(dplyr)
library(forcats)
library(ggplot2)
library(gghighlight)

db <- combine_fude(d, b, city = "жқҫеұұеёӮ", kcity = "иҲҲеұ…еі¶", community = "^(?!йҮЈеі¶)")

db$community <- db$community |>
  mutate(across(c(RCOM_NAME, RCOM_KANA, RCOM_ROMAJI), forcats::fct_rev))
db$fude <- db$fude |>
  mutate(across(c(RCOM_NAME, RCOM_KANA, RCOM_ROMAJI), forcats::fct_rev))

ggplot() +
  geom_sf(data = db$community, aes(fill = RCOM_NAME), alpha = 0) +
  geom_sf(data = db$fude, aes(fill = RCOM_NAME), linewidth = 0) +
  gghighlight() +
  facet_wrap(~ RCOM_NAME) +
  theme_void() +
  theme(
    legend.position = "none",
    text = element_text(family = "Hiragino Sans")
  )
```

**еҮәе…ё**пјҡ`r cite_fude(db)$ja`

```{r facet_wrap_gogoshima_hist, echo = TRUE, warning = FALSE, message = FALSE, dpi = 150}
ggplot(data = db$fude, aes(x = a, fill = land_type_jp)) +
  geom_histogram(position = "identity", alpha = .5) +
  labs(x = "йқўз©ҚпјҲaпјү",
       y = "й »еәҰ") +
  facet_wrap(~ RCOM_NAME) +
  labs(fill = "иҖ•ең°гҒ®зЁ®йЎһ") +
  theme_minimal() +
  theme(text = element_text(family = "Hiragino Sans"))
```
